service: aws-serverles

useDotenv: true

plugins:
 - serverless-plugin-typescript
 - serverless-offline
 - serverless-dotenv-plugin

provider:
 name: aws
 runtime: nodejs16.x
 environment:
    POSTGRES_HOST: ${env:POSTGRES_HOST}
    POSTGRES_PORT: ${env:POSTGRES_PORT}
    POSTGRES_USERNAME: ${env:POSTGRES_USERNAME}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
    POSTGRES_DATABASE: ${env:POSTGRES_DATABASE}

functions:
 main: 
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
