service: aws-serverles

plugins:
 - serverless-plugin-typescript
 - serverless-offline

provider:
 name: aws
 runtime: nodejs16.x

functions:
 main: 
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
